# PLAY level variables
#This is play level (defining variables in play level and using in task)
- name: Variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOpsfromplaylevel"
    Trainer: "sivakumarfromplaylevel"
    Duration: "110HRSfromplaylevel"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
