- name: variables from All level
  hosts: localhost
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: PERSON
    prompt: Please enter your name
    private: false # user can see what they are entering
  - name: WISHES
    prompt: please enter your wishes
    private: false # user can't see what they are entering
  vars:
    PERSON: "Siva from PLAY"
    WISHES: "Morning from PLAY"
  tasks:
  - name: check variables
    vars:
      PERSON: "Siva from TASK"
      WISHES: "Morning from TASK"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"

#We will mention the same variables in play level, task level, in var_files i.e.,variable file, in inventory.ini file and in vars_prompt ie.,prompt file
#By default, always command line variables values are the highest priority in any programming language